### ISSUE TITLE
Possibility to use -u (user) option in docker exec

### ISSUE THREAD

**Issue by GeneralTao2** [offen/docker-volume-backup#202]
**Is your feature request related to a problem? Please describe.**
I face a case where a usage of user in docker exec command option is crucial. It must be used in [Gitea dump process](https://docs.gitea.io/en-us/backup-and-restore/#using-docker-dump) to make a backup. The thing is that Gitea doesn't allow performing backup from root user, so a special user is required. I didn't manage to change user in command itself and perform a successful backup. 

**Describe the solution you'd like**
Add a `docker-volume-backup.user` label to specify user option for docker exec. If the label will be empty, then don't pass any user.

**Describe alternatives you've considered**
Nothing in mind

**Additional context**
Nothing to add

**Comment by m90** [comment]
Considering the use case, I think your proposal makes sense. The only thing I wonder is whether it could be required to allow for different user values for different lifecycle values. I.e. instead of using `docker-volume.backup.user` labels, `docker-volume-backup.archive-post.user` could be used to define the user that runs `archive-post` commands. This might be a bit more tedious, but would cover all scenarios, no matter how quirky they might be.

Would you be interested in adding this feature? I'd be happy to help with reviews and and getting it released.

**Comment by GeneralTao2** [comment]
Thank you. Yea, I am working on PR. It will take some time due to low Go language knowledge. I will work  on `docker-volume-backup.archive-pre.user` and `docker-volume-backup.archive-post.user` case.

**Comment by m90** [comment]
Great, let me know if you need any help with that.

**Comment by m90** [comment]
This is now possible as of v2.26.0: https://github.com/offen/docker-volume-backup/releases/tag/v2.26.0
