### ISSUE TITLE
Build for ARM Architectures

### ISSUE THREAD

**Issue by chrismeller** [offen/docker-volume-backup#3]
I'd love to use this to back up some projects I've got running on Raspberry Pi's. Would it be possible to switch to Docker buildx and publish for arm/v7 and arm64 as well?

**Comment by m90** [comment]
Building for ARM sounds like a great idea, although I don't know too much about how to do it.

From what I understand there are two options:
1. Use buildx
2. Add a second job to the CircleCI setup that runs on ARM hardware (although I would assume this is arm64 only)

I'd be happy to look into this, but it might take a while. If you wanna give it a go in the meantime, I am happy to review and merge PRs.

Relevant place for doing this is probably https://github.com/offen/docker-volume-backup/blob/84afc43fd848da66a2ea6a309423ce32e21d7f04/.circleci/config.yml#L26-L30

**Comment by chrismeller** [comment]
Ok, cool, I can take a look at it sometime this week.

I don't know anything about CircleCI, so I have no idea what kind of ARM architectures they support. I know you can do this on any host using QEMU through buildx. I've done that on Github Actions, so it's probably the approach I'll try to go with.

**Comment by m90** [comment]
> I've done that on Github Actions, so it's probably the approach I'll try to go with.

If switching to GitHub actions helps you get this set up, I'd be totally fine with ditching CircleCI here. I guess we can push to Docker Hub from anywhere.

Thank you!

**Comment by m90** [comment]
I just had some time to look into this myself and got buildx working on CircleCI https://github.com/offen/docker-volume-backup/compare/multiarch

There are however some issues still that I currently don't know how to resolve:
- the `mc` MinIO client is only available for arm64 so this is a hard limit for what this repo can build
- the arm64 build never passes, but seems to fail at different stages. Sometimes it fails to run `apk add`, sometimes it fails later when downloading the `mc` executable (sth along the lines of "connection reset by peer").  I assume this is some Networking issue caused by Docker in Docker in Docker (yes, this is what is happening) or similar

It would be interesting to know if:
- does this build successfully in GitHub actions?
- does this build successfully when "unboxed" in CircleCI and run in a machine executor instead of a Docker one?

**Comment by m90** [comment]
Another very strange detail here: when using an `http` (instead of `https`) URL for downloading the MinIO client in the Dockerfile I can get the arm64 build to pass sometimes (unless it fails earlier).

**Comment by m90** [comment]
Upstream issue is here https://github.com/docker/buildx/issues/660

**Comment by m90** [comment]
Ok, this required some serious voodoo as per: https://gitlab.alpinelinux.org/alpine/aports/-/issues/12406 but it seems to be working for `arm64` now and `v1.4.0` is published to Docker Hub, supporting multiple architectures.

If anyone has an idea how to make this work for `arm/v7 et al` too, I would be happy to learn about your ideas.

**Comment by m90** [comment]
`arm/v7` works when the build compiles `mc` from source. [v1.5.0](https://hub.docker.com/layers/offen/docker-volume-backup/v1.5.0/images/sha256-2c5e9e2e33a4fa03d4e9a35ba9e39730d4b64b2b4b649cc2a33c969f62d3a359?context=explore) is now available for `amd64`, `arm64` and `arm/v7`.
