### ISSUE TITLE
Resolve date in AWS_S3_PATH

### ISSUE THREAD

**Issue by Simusharp** [offen/docker-volume-backup#397]
**Is your feature request related to a problem? Please describe.**
When backing up, I prefer to create a S3 path with a time stamp. Unfortunately, using `%Y` in path variable doesn't resolve.

**Describe the solution you'd like**
I would like to set path as follows: `AWS_S3_PATH="backup-%Y-%m-%d"` and have it resolve to `backup-2024-03-21`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by m90** [comment]
Implementing this would be a breaking change, and putting it behind a flag seems too specific for me right now.

I am aware that variable expansion / templating in configuration values currently is way too piece-meal, but there's no easy way out unless the changes made are breaking. I do consider unifying this in a v3 in any case: https://github.com/offen/docker-volume-backup/issues/80

In case you really need the date in the directory instead of the filename, you could use the following workaround:
- Create a Docker image based off this one and install either the AWS CLI or the MinIO client
- In a labeled `copy-post` command on the backup container itself, `mv` the file that has been created to the desired location
