### ISSUE TITLE
Allow specification of AWS region

### ISSUE THREAD

**Issue by amorphic** [offen/docker-volume-backup#50]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request

* **What is the current behavior?**

Currently it _appears_ that the destination S3 bucket is assumed to be in the default `us-east-1` region. I've not found a way to specify otherwise (apologies if I've missed something).

* **If the current behavior is a bug, please provide the configuration and steps to reproduce and if possible a minimal demo of the problem.**

Setting `AWS_S3_BUCKET_NAME` to a bucket in a region other than `us-east-1` results in an error:

```
Fatal error running backup: copyBackup: error uploading backup to remote storage: Put \"https://<AWS_S3_BUCKET_NAME>.s3.dualstack.us-east-1.amazonaws.com/<BACKUP_FILENAME>\": 301 response missing Location header"                                                                                                          
```

* **What is the expected behavior?**

An AWS region can be specified (probably via `AWS_S3_BUCKET_REGION` or similarly-named env var) and the backup is uploaded to the bucket with `AWS_S3_BUCKET_NAME` in that region.

* **What is the motivation / use case for changing the behavior?**

Using this backup tool in regions other than `us-east-1`

Thanks for your work on what is a very comprehensive backup solution for docker volumes! :smiley:

**Comment by m90** [comment]
I just tried reproducing this and couldn't. I created a bucket in `eu-west-1` and was able to store a backup there without any additional configuration:

```yml
AWS_ACCESS_KEY_ID: XXX
AWS_SECRET_ACCESS_KEY: yyy
AWS_S3_BUCKET_NAME: backup-regiontest
```

This is also what I would expect as the global bucket namespace should make specifying a region optional.

Could it be that your credentials contain a typo or are lacking permissions? See: https://github.com/minio/minio-go/issues/1132 and also https://github.com/offen/docker-volume-backup/issues/11

In case that does not fix the issue for you could you:
- try providing a region specific endpoint to `AWS_ENDPOINT` instead of the default one (https://docs.aws.amazon.com/general/latest/gr/rande.html)
- provide your full configuration here so I can try to reproduce thiss

**Comment by amorphic** [comment]
Thanks @m90 for the quick response and apologies that I didn't get back to you sooner.

I ended up finding a different solution and so didn't delve any deeper. But FYI in case it comes up again in future the one thing that I did confirm were that the credentials were entered correctly and had the required permissions.
