### ISSUE TITLE
Passing cron schedule in docker compose file

### ISSUE THREAD

**Issue by MRIIOT** [offen/docker-volume-backup#84]
Just a note.

This works:

```
environment:
      - BACKUP_CRON_EXPRESSION=* 9 * * *
```

This does not:

```
environment:
      - BACKUP_CRON_EXPRESSION="* 9 * * *"
```

**Comment by m90** [comment]
`docker-compose` notations can be very complicated (e.g. #57). Personally, I usually use object notation for environment variables which seem to be a bit more forgving:

```yml
environment:
      BACKUP_CRON_EXPRESSION: * 9 * * *
```

and which works well for both quoted an unquoted values. This is also the notation used in the documentation, so I guess there's not too much I can do here.

On a side note this might also be caused by an outdated compose version as per https://github.com/docker/compose/issues/2854
